# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all 
Song.destroy_all 
Genre.destroy_all
Mood.destroy_all 
Playlist.destroy_all 
# User data 
barryallen = User.create(username: "Barry Allen") 
# Genre data 
desi = Genre.create(genre_type: "Desi") #1
hiphop = Genre.create(genre_type: "Hip-Hop") #2
pop = Genre.create(genre_type: "Pop") #3
country = Genre.create(genre_type: "Country") #4
rb = Genre.create(genre_type: "R&B") #5
latin = Genre.create(genre_type: "Latin") #6  
rock = Genre.create(genre_type: "Rock") #7
dance = Genre.create(genre_type: "Dance/Electronic") #8
indie = Genre.create(genre_type: "Indie") #9
folk = Genre.create(genre_type: "Folk & Accoustic") #10 
classical = Genre.create(genre_type: "Classical") #11
jazz = Genre.create(genre_type: "Jazz") #12
soul = Genre.create(genre_type: "Soul") #13
christian = Genre.create(genre_type: "Christian") #14
kpop = Genre.create(genre_type: "K-Pop") #15
regionalmexican = Genre.create(genre_type: "Regional Mexican") #16 
arab = Genre.create(genre_type: "Arab") #17
anime = Genre.create(genre_type: "Anime") #18
afro = Genre.create(genre_type: "Afro") #19
tvandmovies = Genre.create(genre_type: "TV & Movies") #20
metal = Genre.create(genre_type: "Metal") #21
reggae = Genre.create(genre_type: "Reggae") #22
blues = Genre.create(genre_type: "Blues") #23
punk = Genre.create(genre_type: "Punk") #24
funk = Genre.create(genre_type: "Funk") #25
kidsandfamily = Genre.create(genre_type: "Kids & Family") #26
# Mood data 
summer = Mood.create(mood_type: "Summer") #1
fall = Mood.create(mood_type: "Fall") #2
winter = Mood.create(mood_type: "Winter") #3 
spring = Mood.create(mood_type: "Spring") #4
workout = Mood.create(mood_type: "Workout") #5
nineties = Mood.create(mood_type: "90s") #6
gaming = Mood.create(mood_type: "Gaming") #7
commute = Mood.create(mood_type: "Commute") #8
home = Mood.create(mood_type: "Home") #9
focus = Mood.create(mood_type: "Focus") #10
chill = Mood.create(mood_type: "Chill") #11
happy = Mood.create(mood_type: "Happy") #12
angry = Mood.create(mood_type: "Angry") #13
sad = Mood.create(mood_type: "Sad") #14
wellness = Mood.create(mood_type: "Wellness") #15 
party = Mood.create(mood_type: "Party") #16
cookinganddining = Mood.create(mood_type: "Cooking & Dining") #17
romance = Mood.create(mood_type: "Romance") #18
# Song data 
aankhmarey = Song.create(name: "Aankh Marey", artist: "Mika Singh, Neha Kakkad, Kumar Sanu", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Aankh Marey.mp3") 
ac_dc_thunderstruck = Song.create(name: "Ankh Marey", artist: "AC DC", genre_id: 7, mood_id: 5, song_url: "moodify-backend/app/assets/AC_DC - Thunderstruck (Official Video).mp3") 
adhuralafz = Song.create(name: "Adhura Lafz", artist: "Rahat Fateh Ali Khan", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Adhura Lafz.mp3") 
afghanjalebi = Song.create(name: "Afghan Jalebi", artist: "Asrar", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Afghan Jalebi.mp3") 
ajr_100baddays = Song.create(name: "100 Bad Days", artist: "AJR", genre_id: 8, mood_id: 13, song_url: "moodify-backend/app/assets/AJR - 100 Bad Days.mp3") 
akelinabazaar = Song.create(name: "Akeli Na Bazaar", artist: "Udit Narayan", genre_id: 1, mood_id: 6, song_url: "moodify-backend/app/assets/Akeli-Na-Bazaar-Jaaya-Kero.mp3") 
alanwalker_alone = Song.create(name: "Alone", artist: "Alan Walker", genre_id: 8, mood_id: 7, song_url: "moodify-backend/app/assets/Alan Walker - Alone.mp3") 
anisdondemina = Song.create(name: "For Stora For Den Har Stan", artist: "Anis Don Demina", genre_id: 8, mood_id: 16, song_url: "moodify-backend/app/assets/Anis Don Demina - För stora för den här stan (feat. Mapei) (CLEAN VERSION).mp3") 
anuelaakarolg = Song.create(name: "Secreto", artist: "Anuel AA, Karol G", genre_id: 6, mood_id: 10, song_url: "moodify-backend/app/assets/Anuel AA, KAROL G - Secreto.mp3") 
apnatime = Song.create(name: "Apna Time Aayega", artist: "Ranveer Singh", genre_id: 1, mood_id: 10, song_url: "moodify-backend/app/assets/Apna Time Aayega.mp3") 
bekhayali = Song.create(name: "Bekhayali", artist: "Sachet Tandon", genre_id: 1, mood_id: 13, song_url: "moodify-backend/app/assets/Bekhayali.mp3") 
bryanadams = Song.create(name: "Summer of '69", artist: "Bryan Adams", genre_id: 7, mood_id: 11, song_url: "moodify-backend/app/assets/Bryan Adams - Summer Of '69 (Official Music Video).mp3")
buddhusamann = Song.create(name: "Buddhu Sa Mann", artist: "Armaan Malik", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Buddhu Sa Mann.mp3")
chaandtaare = Song.create(name: "Chaand Taare", artist: "Abhijeet", genre_id: 1, mood_id: 10, song_url: "moodify-backend/app/assets/Chaand-Taare.mp3")
derezzed = Song.create(name: "Derezzed", artist: "Daft Punk", genre_id: 20, mood_id: 7, song_url: "moodify-backend/app/assets/Daft Punk- Derezzed (OFFICIAL TRACK)(FULL SONG)(HQ)(2010)TRON SOUNDTRACK.mp3") 
daryaa = Song.create(name: "Daryaa", artist: "Ammy Virk, Shahid Mallya", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Daryaa.mp3")
dekhtedekhterahat = Song.create(name: "Dekhte Dekhte (Rahat Fateh Ali Khan version)", artist: "Rahat Fateh Ali Khan", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Dekhte Dekhte (Rahat Fateh Ali Khan Version).mp3") 
dekhtedekhte = Song.create(name: "Dekhte Dekhte", artist: "Atif Aslam", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Dekhte Dekhte.mp3")  
dilcheez = Song.create(name: "Dil Cheez Tujhe Dedi", artist: "Arijit Singh, Ankit Tiwari", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Dil Cheez Tujhe Dedi.mp3") 
dilchori = Song.create(name: "Dil Chori", artist: "Yo Yo Honey Singh", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Dil Chori.mp3") 
dilmerinasune = Song.create(name: "Dil Meri Na Sune", artist: "Atif Aslam", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Dil Meri Na Sune.mp3") 
danzakuduro = Song.create(name: "Danza Kuduro", artist: "Don Omar", genre_id: 6, mood_id: 16, song_url: "moodify-backend/app/assets/Don Omar - Danza Kuduro ft. Lucenzo.mp3")
dontstopmenow = Song.create(name: "Don't Stop Me Now", artist: "Queen", genre_id: 7, mood_id: 5, song_url: "moodify-backend/app/assets/Don't Stop Me Now.mp3") 
drakeonedance = Song.create(name: "One Dance", artist: "Drake", genre_id: 2, mood_id: 16, song_url: "moodify-backend/app/assets/Drake - One Dance.mp3") 
elniagara = Song.create(name: "El Niagara En Bicicleta", artist: "Juan Luis Guerra", genre_id: 6, mood_id: 14, song_url: "moodify-backend/app/assets/El Niagara En Bicicleta.mp3") 
elviscanthelp = Song.create(name: "Can't Help Falling in Love", artist: "Elvis Presley", genre_id: 7, mood_id: 14, song_url: "moodify-backend/app/assets/Elvis Presley - Can't Help Falling In Love (Audio).mp3") 
bailando = Song.create(name: "Bailando (English)", artist: "Enrique Iglesias ft. Sean Paul", genre_id: 6, mood_id: 16, song_url: "moodify-backend/app/assets/Enrique Iglesias Ft. Sean Paul - Bailando (English).mp3") 
filhall = Song.create(name: "Filhall", artist: "BPraak", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Filhall.mp3") 
fleetwooddreams = Song.create(name: "Dreams - 2004 Remaster", artist: "Fleetwood Mac", genre_id: 7, mood_id: 11, song_url: "moodify-backend/app/assets/Fleetwood Mac - Dreams.mp3") 
gallankardi = Song.create(name: "Gallan Kardi", artist: "Jazzy B, Jyotica Tangri, Mumzy Stranger", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Gallan Kardi.mp3") 
ghungroo = Song.create(name: "Ghungroo", artist: "Arijit Singh, Shilpa Rao", genre_id: 1, mood_id: 11, song_url: "moodify-backend/app/assets/Ghungroo.mp3") 
hozieralmost = Song.create(name: "Almost (Sweet Music)", artist: "Hozier", genre_id: 12, mood_id: 14, song_url: "moodify-backend/app/assets/Hozier - Almost (Sweet Music) (Audio).mp3") 
humraah = Song.create(name: "Humraah", artist: "Sachet Tandon", genre_id: 1, mood_id: 10, song_url: "moodify-backend/app/assets/Humraah.mp3") 
imnotokay = Song.create(name: "I'm Not Okay(I Promise)", artist: "My Chemical Romance", genre_id: 7, mood_id: 13, song_url: "moodify-backend/app/assets/I'm Not Okay (I Promise).mp3") 
ikmulaqaat = Song.create(name: "Ik Mulaqaat", artist: "Altamash Faridi, Palak Mucchal", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Ik Mulaqaat.mp3") 
illegalweapon = Song.create(name: "Illegal Weapon", artist: "Gary Sandhu, Jasmine Sandlas", genre_id: 1, mood_id: 11, song_url: "moodify-backend/app/assets/Illegal Weapon.mp3") 
jbalvinginza = Song.create(name: "Ginza - Atellagali In Da House", artist: "J Balvin", genre_id: 6, mood_id: 7, song_url: "moodify-backend/app/assets/J. Balvin - Ginza (Atellagali In Da House Remix_Audio).mp3") 
lacancion = Song.create(name: "La Cancion", artist: "J Balvin, Bad Bunny", genre_id: 6, mood_id: 11, song_url: "moodify-backend/app/assets/J. Balvin, Bad Bunny - LA CANCIÓN (Audio).mp3") 
middlechild = Song.create(name: "Middle Child", artist: "J.Cole", genre_id: 2, mood_id: 10, song_url: "moodify-backend/app/assets/J. Cole - MIDDLE CHILD.mp3") 
jeekarda = Song.create(name: "Jee Karda", artist: "Divya Kumar", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Jee Karda.mp3") 
themiddle = Song.create(name: "The Middle", artist: "Jimmy Eat the World", genre_id: 3, mood_id: 10, song_url: "moodify-backend/app/assets/Jimmy Eat World - The Middle (Official Music Video).mp3") 
jotunamila = Song.create(name: "Jo Tu Na Mila", artist: "Asim Azhar", genre_id: desi, mood_id: sad, song_url: "moodify-backend/app/assets/Jo Tu Na Mila.mp3") 
jtonyou = Song.create(name: "You're The One I Want", artist: "John Travolta, Olivia Newton John", genre_id: 20, mood_id: 16, song_url: "moodify-backend/app/assets/John Travolta And Olivia Newton John - You're The One That I Want.mp3") 
jojisanctuary = Song.create(name: "Sanctuary", artist: "Joji", genre_id: 3, mood_id: 11, song_url: "moodify-backend/app/assets/Joji - Sanctuary (Lyrics).mp3")
jummachumma = Song.create(name: "Jumma Chumma", artist: "Sudesh Wadkar", genre_id: 1, mood_id: 6, song_url: "moodify-backend/app/assets/Jumma-Chumma-De-De.mp3") 
kyamujhepyaar = Song.create(name: "Kya Mujhe Pyaar Hai", artist: "KK", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Kya Mujhe Pyar.mp3") 
lacamisanegra = Song.create(name: "La Camisa Negra", artist: "Juanes", genre_id: 6, mood_id: 13, song_url: "moodify-backend/app/assets/La Camisa Negra.mp3") 
lalala = Song.create(name: "La La La", artist: "Bilal Saeed, Neha Kakkad", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/La La La.mp3") 
lahore = Song.create(name: "Lahore", artist: "Guru Randhawa", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Lahore.mp3") 
lamberghini = Song.create(name: "Lamberghini", artist: "Doorbeens ft. Ragini", genre_id: 1, mood_id: 11, song_url: "moodify-backend/app/assets/Lamberghini.mp3") 
lehanga = Song.create(name: "Lehanga", artist: "Jass Manak", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Lehanga.mp3") 
mamasaid = Song.create(name: "Mama Said Knock You Out", artist: "LL Cool J", genre_id: 2, mood_id: 5, song_url: "moodify-backend/app/assets/LL Cool J - Mama Said Knock You Out (Official Video).mp3") 
losafar = Song.create(name: "Lo Safar", artist: "Jubin Nautiyal", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Lo Safar.mp3") 
lorynstandby = Song.create(name: "Stand By", artist: "Loryn", genre_id: 3, mood_id: 7, song_url: "moodify-backend/app/assets/LORYN - Stand By (#CWC19) (Official Video) ft. Rudimental.mp3") 
madeindia = Song.create(name: "Made in India", artist: "Guru Randhawa", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Made In India.mp3") 
mmgoingbad = Song.create(name: "Going Bad", artist: "Meek Mill ft. Drake", genre_id: 2, mood_id: 13, song_url: "moodify-backend/app/assets/Meek Mill - Going Bad feat. Drake (Official Video).mp3") 
merebina = Song.create(name: "Mere Bina", artist: "Nikhil D'Souza", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Mere Bina.mp3") 
mererashke = Song.create(name: "Mere Rashke Qamar", artist: "Junaid Asghar", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Mere Rashke Qamar.mp3") 
maniac = Song.create(name: "Maniac", artist: "Michael Sembello", genre_id: 7, mood_id: 13, song_url: "moodify-backend/app/assets/Michael Sembello - Maniac.mp3")
mornibanke = Song.create(name: "Morni Banke", artist: "Guru Randhawa", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Morni Banke.mp3")
naja = Song.create(name: "Na Ja", artist: "Pav Dharia", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Na Ja - Songs.pk - 320Kbps.mp3") 
nashesi = Song.create(name: "Nashe Si Chadh Gayi", artist: "Arijit Singh", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Nashe Si Chadh Gayi.mp3")
nazarnalagjaaye = Song.create(name: "Nazar Na Lag Jaaye", artist: "Ash King", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Nazar Na Lag Jaaye.mp3") 
nazmnazm = Song.create(name: "Nazm Nazm", artist: "Arko", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Nazm Nazm.mp3") 
neovalieasily = Song.create(name: "Easily", artist: "Neovali", genre_id: 8, mood_id: 7, song_url: "moodify-backend/app/assets/Neovaii - Easily.mp3") 
nujabes = Song.create(name: "Reflection Eternal", artist: "Nujabes", genre_id: 8, mood_id: 11, song_url: "moodify-backend/app/assets/Nujabes - Reflection Eternal.mp3") 
osaathi = Song.create(name: "O Saathi", artist: "Atif Aslam", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/O Saathi.mp3") 
ojaanejaana = Song.create(name: "O Jaane Jaana", artist: "Kamaal Khan", genre_id: 1, mood_id: 6, song_url: "moodify-backend/app/assets/O-Jaane-Jaana.mp3") 
pal = Song.create(name: "Pal", artist: "Arijit Singh, Shreya Ghoshal", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Pal.mp3") 
papakehtehain = Song.create(name: "Papa Kehte Hain", artist: "Udit Narayan", genre_id: 1, mood_id: 10, song_url: "moodify-backend/app/assets/Papa-Kehte-Hain.mp3") 
patakay = Song.create(name: "Patakay", artist: "Amar Sandhu ft. Ezu", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Patakay.mp3") 
pehlinazarmein = Song.create(name: "Pehli Nazar Mein", artist: "Atif Aslam", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Pehli Nazar Mein.mp3") 
peroyano = Song.create(name: "Pero Ya No", artist: "Bad Bunny", genre_id: 6, mood_id: 14, song_url: "moodify-backend/app/assets/Pero Ya No - Bad Bunny ( Video Oficial ).mp3") 
pwhappy = Song.create(name: "Happy", artist: "Pharrell Williams", genre_id: 3, mood_id: 12, song_url: "moodify-backend/app/assets/Pharrell Williams - Happy (Lyrics).mp3") 
phirnamilenkabhi = Song.create(name: "Phir Na Milen Kabhi", artist: "Ankit Tiwari", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Phir Na Milen Kabhi.mp3") 
pyaarkarke = Song.create(name: "Pyaar Karke Pachtaya", artist: "Labh Janjua", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Pyaar Karke Pachtaya.mp3") 
queenanotherone = Song.create(name: "Another One Bites The Dust", artist: "Queen", genre_id: 7, mood_id: 10, song_url: "moodify-backend/app/assets/Queen - Another One Bites the Dust (Official Video).mp3") 
redbonecome = Song.create(name: "Come and Get Your Love", artist: "Redbone", genre_id: 7, mood_id: 12, song_url: "moodify-backend/app/assets/Redbone - Come and Get Your Love (Official Audio).mp3") 
rockthaparty = Song.create(name: "Rock Tha Party", artist: "Bombay Rockers", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Rock Tha Party.mp3") 
rudeeternal = Song.create(name: "Eternal Youth", artist: "Rude", genre_id: 7, mood_id: 11, song_url: "moodify-backend/app/assets/RUDE - Eternal Youth.mp3")
saddahaq = Song.create(name: "Sadda Haq", artist: "Mohit Chauhan", genre_id: 1, mood_id: 13, song_url: "moodify-backend/app/assets/Sadda Haq.mp3")
sanuekpalchain = Song.create(name: "Sanu Ek Pal Chain", artist: "Rahat Fateh Ali Khan", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Sanu Ek Pal Chain.mp3") 
sauaasman = Song.create(name: "Sau Aasmaan", artist: "Armaan Malik, Neeti Mohan", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Sau Aasmaan.mp3") 
senorita = Song.create(name: "Senorita", artist: "Farhan Akhtar, Hrithik Roshan", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Senorita.mp3") 
schantaje = Song.create(name: "Chantaje", artist: "Shakira ft. Maluma", genre_id: 6, mood_id: 5, song_url: "moodify-backend/app/assets/Shakira - Chantaje (Audio) ft. Maluma.mp3") 
swakawaka = Song.create(name: "Waka Waka", artist: "Shakira", genre_id: 6, mood_id: 16, song_url: "moodify-backend/app/assets/Shakira-Waka Waka.mp3")
shingluv = Song.create(name: "Luv(sic)", artist: "Nujabes", genre_id: 6, mood_id: 11, song_url: "moodify-backend/app/assets/Shing02 - Luv (sic).mp3") 
sipsip = Song.create(name: "Sip Sip", artist: "Jasmine Sandlas", genre_id: 1, mood_id: 5, song_url: "moodify-backend/app/assets/Sip Sip.mp3") 
slowly = Song.create(name: "Slowly Slowly", artist: "Guru Randhawa ft. Pitbull", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Slowly Slowly.mp3")
soniyedilnayi = Song.create(name: "Soniye Dil Nayi", artist: "Ankit Tiwari", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Soniye Dil Nayi.mp3") 
subahsubah = Song.create(name: "Subah Subah", artist: "Arijit Singh", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Subah Subah.mp3") 
suitsuit = Song.create(name: "Suit Suit", artist: "Guru Randhawa ft. Arjun", genre_id: 1, mood_id: 5, song_url: "moodify-backend/app/assets/Suit Suit.mp3") 
tareefan = Song.create(name: "Tareefan", artist: "Badshah", genre_id: 1, mood_id: 5, song_url: "moodify-backend/app/assets/Tareefan.mp3") 
terabanjaunga = Song.create(name: "Tera Ban Jaunga", artist: "Akhil Sachdeva, Tulsi Kumar", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/Tera Ban Jaunga.mp3") 
terafitoor = Song.create(name: "Tera Fitoor", artist: "Arijit Singh", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Tera Fitoor.mp3") 
terahua = Song.create(name: "Tera Hua", artist: "Atif Aslam", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Tera Hua.mp3") 
terebin = Song.create(name: "Tere Bin", artist: "Rahat Fateh Ali Khan", genre_id: 1, mood_id: 18, song_url: "moodify-backend/app/assets/Tere Bin.mp3") 
thatrickhood = Song.create(name: "Hood Bodega", artist: "Tha Trickaz", genre_id: 1, mood_id: 7, song_url: "moodify-backend/app/assets/Tha Trickaz - Hood Bodega.mp3") 
theboynext = Song.create(name: "La Colegiala", artist: "The Boy Next Door", genre_id: 8, mood_id: 16, song_url: "moodify-backend/app/assets/Tha Trickaz - Hood Bodega.mp3") 
thehummasong = Song.create(name: "The Humma Song", artist: "Jubin Nautiyal", genre_id: 1, mood_id: 12, song_url: "moodify-backend/app/assets/The Humma Song.mp3")
thejacksons = Song.create(name: "Blame It On The Boogie", artist: "The Jacksons", genre_id: 3, mood_id: 12, song_url: "moodify-backend/app/assets/The Jacksons - Blame It On the Boogie (Official Video).mp3") 
thodijagah = Song.create(name: "Thodi Jagah", artist: "Arijit Singh", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Thodi Jagah.mp3") 
throttlecities = Song.create(name: "Cities", artist: "Throttle", genre_id: 8, mood_id: 7, song_url: "moodify-backend/app/assets/Throttle - Cities.mp3") 
tumhiaana = Song.create(name: "Tum Hi Aana", artist: "Jubin Nautiyal", genre_id: 1, mood_id: 14, song_url: "moodify-backend/app/assets/Tum Hi Aana.mp3")
uffteriada = Song.create(name: "Uff Teri Ada", artist: "Shankar Mahadevan, Alyssa Mendonza", genre_id: 1, mood_id: 11, song_url: "moodify-backend/app/assets/Uff Teri Ada.mp3") 
woofer = Song.create(name: "Woofer", artist: "Snoop Dogg, Dr. Zeus, Zora Randhawa", genre_id: 1, mood_id: 16, song_url: "moodify-backend/app/assets/Woofer.mp3") 
xxxsad = Song.create(name: "SAD!", artist: "Xxxtentacion", genre_id: 6, mood_id: 14, song_url: "moodify-backend/app/assets/XXXTENTACION - SAD! (Official Music Video).mp3") 
xxxwhoa = Song.create(name: "Woah(Mind in Awe)", artist: "Xxxtentacion", genre_id: 6, mood_id: 5, song_url: "moodify-backend/app/assets/XXXTENTACION - whoa (mind in awe) (Audio).mp3")
yekalikali = Song.create(name: "Ye Kali Kali", artist: "Kumar Sanu", genre_id: 1, mood_id: 6, song_url: "moodify-backend/app/assets/Ye-Kali-Kali.mp3") 
